### ISSUE TITLE
Add life safety devices to MCLA Essentials

### ISSUE THREAD

**Issue by hawka97** [hawka97/mcla-modpack#40]
This includes many styles of pull station, speaker strobe, strobe only, speaker only, and heat and smoke detectors, including fire alarm panels as well. This should also include home fire protection as well, such as Nest Protect, and other home fire and smoke detector devices.

**Comment by hawka97** [comment]
This is a work in progress. I am gathering the images and storing them in the repository. @rinrincodes see https://github.com/hawka97/mcla-mod/commit/c0476b06b52eddc1e2b96cbac14ced5c7caf5340#diff-1bc27c5a998409186468405125856de0

**Comment by rinrincodes** [comment]
Ok good. Btw this will become a seperate mod once again as essentials is usually for general everyday stuff you'd normally find.

**Comment by rinrincodes** [comment]
Will be added later on in 1.4 or 1.5. I haven't decided yet but those versions will be where the life safety stuff will go.
